# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('tweet_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(max_length=250)),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
            ],
        ),
    ]
