# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_csv', '0002_auto_20170523_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
