# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_csv', '0003_auto_20170523_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(unique=True),
        ),
    ]
