# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

# La clave es el valor por el cual se va a reemplazar la abreviatura
# La lista de valores son las abreviaturas que existen

palabras = {"siempre": ['100pre',"always"],
            "por que": ["xq"],
            "adiós": ["a10","a2","bye","chao","chau","goodbye","dew","dw"],
            "hace": ["ac"],
            "aquí": ["aki","here"],
            "amor": ["amr","love"],
            "ahora": ["aora","now"],
            "al salir de clase": ["asdc"],
            "gracias": ["asias","thanks"],
            "bien": ["b","well"],
            "bebé": ["bb","baby"],
            "beber": ["bbr"],
            "besos": ["bs","bss","kisses"],
            "besitos": ["kisses","b7s"],
            "se": ["c"],
            "cámara": ["cam","camera"],
            "cuando": ["cdo","when"],
            "de": ["d",""],
            "hace": ["ac","from","of"],
            "dedos": ["d2","fingers"],
            "decir": ["dcr","to say"],
            "difícil": ["dfcl","difficult"],
            "hemos": ["ems","We have"],
            "dónde": ["dnd","where"],
            "eres":["ers"],
            "eres tú": ["ers","ers2"],
            "hecho": ["exo","act"],
            "ellos": ["eys"],
            "fin de semana": ["finde","weekend"],
            "fiesta": ["fsta","party"],
            "enfadado": ["grrr","angry"],
            "hasta luego": ["hl","see you later"],
            "igual": ["iwal","equal"],
            "que": ["k"],
            "hola": ["hla","hello"],
            "cabeza": ["kbza","head"],
            "clase": ["kls","class"],
            "como": ["km"],
            "cuéntame": ["kntm"],
            "estoy muerto": ["KO"],
            "cállate": ["kyat"],
            "mándame un mensaje luego": ["m1ml"],
            "misión imposible": ["mim"],
            "mensaje": ["msj","sms"],
            "mucho": ["mxo"],
            "no puedo hablar": ["nph","hello"],
            "no pasa nada":["npn"],
            "para": ["pa"],
            "poco": ["pco"],
            "piérdete": ["pdt"],
            "por favor": ["pf","please"],
            "porqué": ["pq","xq"],
            "que": ["q","k"],
            "¿Qué haces?": ["q acs?"],
            "se": ["c"],
            "cámara": ["cam","hello"],
            "cuando": ["cdo","qand","qando"],
            "de": ["d"],
            "dedos": ["d2"],
            "dime": ["dim"],
            "quedamos": ["qdms"],
            "¡Qué plomo!": ["q plomo!"],
            "¿Qué quieres?": ["q qrs?"],
            "¡Qué risa!": ["q risa!"],
            "¿sabes?": ["sbs?"],
            "qué tal": ["q tal?"],
            "saludos": ["salu2","goodbye"],
            "espero": ["spro"],
            "te": ["t"],
            "¿Estás bien?": ["tas OK?"],
            "también": ["tm","tmb"],
            "te quiero": ["tqi"],
            "tengo que irme": ["q tal?"],
            "universidad": ["uni"],
            "vosotros": ["vos?"],
            "¿Vienes?": ["vns?"],
            "¡Guapa!": ["wpa"],
            "perdón?": ["xdon","sorry"],
            "por favor": ["xfa","please"],
            "¿Vienes?": ["vns?"],
            "pero":['xo','but'],
            "llámame":["ymam","ymm"],
            "dormir":['zzz'],

            # Aegentina
            'What’s up?':['¿Qué onda?','¿Como va?'],
            'Cool people':['Piola (adj.)','escrachado/escrachar (verb)'],
            'I love you':['te quiero mucho'],
            'Boy':['Pibe'],
            'Guy/Dude':['Chabón'],
            'Taxi':['Tacho'],
            #Chile
            'What’s up?':['¿Qué más? ','¿Qué hubo?'],
            'Be careful!/Watch out!':['¡Ojo!'],
            'Be careful!':['¡Pilas!'],
            'Ridiculous/uncool':['Mañé'],
            'Anger':['Piedra'],
            'Black coffee':['Tinto'],
            'Police Officer':['Tombo'],
            
            #Cuba
            'How are you doing?':['¿Que es la que hay?'],
            'insanely in love with someone / an act of desperation':['mate'],
            'cute/pretty':['mono'],
            'cents/dollars/money':['chavos'],
            
            #Guatemala
            'What’s up':['¿Qué onda!'],
            'Cool':['Calidá'],
            'Dude/Idiot':['Cerote/Pizado'],
            'I love you lots':['Te quiero mucho'],
            'Boy':['Wirito/Gúirito'],
            'Guy':['Chavo'],
            'Teen girl':['Chava'],
            
            #Mexico
            'What’s up?':['¿Qué Huele?'],
            'Preppie/snob/spoiled brat':['Fresa'],
            'Watch out!':['Aguas'],
            'cool':['Chido'],
            'That’s tight':['Qué padre'],
            'Dude (sometimes pejorative)':['Güey'],
            'What did you say? / Pardon me':['Mande'],
            'Give me a break!':['¡Chale!'],

            # Spain
            'What’s up':['¿Qué pasa?'],
            'No way!':['¡Ni di coña!'],
            'Tourist from North Europe':['Guiri'],
            'Delinquent / pretty theif':['Quinqui/Kinki'],
            'Dude':['Tio / Tia'],
            
            #Peru
            'What’s up?':['¿Que cuentas?'],
            'true':['la firme'],
            'achorado':['defiant'],
            'los vidrios':['see you'],
            'work':['chamba'],
            'bro/dude':['Pata'],
            'jacket':['chompa'],
            'show off':['figureti'],

            # Venezuela
            'squeeze/group together!':['Arrecochínense!'],
            'Get smart! / straighten up!':['¡Avíspate!'],
            'fat belly':['Caucho'],
            'Junk food/quick lunch':['Bala fria'],
            'Awesome':['Candela'],
            'Hangover':['Ratón'],
            'To court someone':['Echar los perros'],
            'French Kiss':['Lata'],

            }



emoticons = {':-)--':'100 pound weakling',
            ':-%':'a banker',
            ':-)-{8':'a big girl',
            ':>)':'a big nose',
            ':-X':'A big wet kiss',
            '*:o)':'a Bozo',
            ':->|':'a cold',
            'o-)':'a cyclops',
            '=:-)':'a hosehead',
            '>:)':'a little devil',
            ':-{':'a mustache',
            ':-)))))))':'A Person With Multiple Chins',
            '[:|]':'a robot',
            '@>--;--':'A Rose',
            ':%)%':'acne',
            ':-=)':'Adolph Hitler',
            ':-s':'after a BIZARRE comment',
            '(ap)':'Airplane',
            ':-o':'Alarmed',
            'OOOOOO':'Alien',
            '(8>/--<':'Alien',
            '(.V.)':'Alien',
            '(.!.)':'Alien',
            ':-O':'Amazement',
            ':-|':'ambivalent',
            ':%)':'an accountant',
            '(:I':'an egghead',
            ':-0':'an orator',
            'O:)':'Angel',
            'O:-)':'Angel',
            'O-)':'Angel',
            '0=)':'Angel',
            '0:-)':'Angel',
            '(a)':'Angel',
            '^j^':'Angel',
            '0*-)':'Angel Wink – Female',
            '0;-)':'Angel Wink – Male',
            'o:-)':'angelic',
            'X(':'Angry',
            'X-(':'Angry',
            'O':'Angry',
            'b (':'Angry',
            '>:-)':'Angry',
            '>:-(':'Angry',
            '(:-&':'Angry',
            ':@':'Angry',
            ':(':'Angry',
            ':-t':'Angry',
            ':-||':'Angry',
            ':-@':'Angry',
            ':-{':'Angry',
            ':-Z':'Angry Face',
            "|_|'":'Anime Sweat Drop',
            '-_-;':'Anime Sweat Drop',
            '^^;':'Anime Sweat Drop',
            '??':'Annoyed',
            '>:-(':'Annoyed',
            '@_@':'Annoyed',
            '(-_-* )':'Annoyed',
            '( o_o)':'Annoyed',
            '<:-I':'another dunce',
            '=D>':'Applause',
            ':*)?':'Are You Drunk?',
            ':*) ?':'Are You Drunk?',
            'l-)':'Asleep',
            '|-I':'asleep',
            '|-)':'asleep (boredom)',
            '~X(':'At Wits End',
            '(-:':'Australian',
            '(au)':'Auto',
            ':o)':'babe the pig',
            ':=8)':'Baboon',
            '~O><':'Baby',
            '~:O':'Baby',
            '~:0':'Baby',
            'X:-)':'bad hair day',
            '~#:-(':'Bad Hair Day',
            '?:-)':'Bad Hair Day',
            '~~8-O':'Bad Hair Day',
            'C:-|':'Bald',
            '(:-)':'Bald',
            '((':'Banana',
            '(::( )::)':'Band-Aid',
            '(::[]::)':'band-aide',
            'o >':'Baring Teeth',
            ':-E':'Baring Teeth',
            'D:-)':'Baseball Cap',
            'q:-)':'Baseball Catcher',
            'd:-)':'Baseball nut',
            'd:-p':'Baseball Player',
            'd:-)':'baseball player',
            ':)':'Basic Little Kid',
            ':-{0':'Basic Mustache',
            '^v^':'Bat',
            'B-)':'Batman',
            ';;)':'Batting Eyelashes',
            '(brb)':'Be Right Back',
            '(brb)':'Bear',
            '(") (")':'Bear',
            ':>)=':'Beard',
            ':)#':'Beard',
            ':-%':'beard',
            ':-){':'Beard',
            '(:-{~':'Beard – Long',
            ':-%':'beard',
            'b-(':'Beat Up',
            '%+|':'Beaten Up',
            ': =':'Beaver',
            '0___':'Bed',
            'X:-|':'Bed Head',
            '%-|':'Been Up All Night',
            '(b)':'Beer Mug',
            '&:-o-8-<':'Betty Boop',
            '(*)/ (*)':'Bicycle',
            '(:-)':'Big Face',
            ':D':'Big Grin',
            ':-D':'Big Grin',
            '>:D<':'Big Hug',
            ':------------)':'big liar',
            '(:+)':'big nose',
            ':>)':'big nose',
            ':))':'big smile',
            ':-(=)':'big teeth',
            ':-X':'Big Wet Kiss',
            '<(:?)':'Big-Nosed Dunce',
            '=|:O}':'Bill Clinton Smiley',
            '~O~':'Bird',
            '(':'Bird',
            '|-O':'Birth',
            '(^)':'Birthday Cake',
            '*<:)':'Birthday Hat',
            ':->':'biting sarcasm',
            ':-]':'biting sarcasm',
            ':-s':'Bizzare Comment',
            '(:<)':'blabber mouth',
            '(:-D':'blabber mouth',
            '?-(':'Black Eye',
            '!-(':'Black Eye',
            '(bah)':'Black Sheep',
            '(:-':'Blank Expression',
            '#-)':'Blinking',
            '^^':'Blissful',
            ':-]':'Blockhead',
            "%')":'blotto',
            ':-{}':'blowing a kiss',
            '`-`':'blown away',
            ':")':'Blush',
            ":,')":'Blushing',
            ':-">':'Blushing',
            '(@_@)':'bog-eyed, or drunk',
            '@=':'Bomb',
            ':-(':'Boo hoo',
            'l-o':'bored',
            '\-o':'bored',
            ':-o':'Bored',
            ':-!':'Bored',
            ':-O ZZ ZZ ZZ':'Bored Or Tired',
            ':-X':'bow tie',
            ':-}X':'Bow Tie-Wearing',
            '(||)':'Bowl',
            '===O____iii':'Bowling',
            "Q(''q) Q(''Q)":'Boxing',
            '(z)':'Boy',
            "( '}{' )":'Boy And Girl Kissing',
            '>:*)':'Bozo the Clown',
            '*:o)':'Bozo the Clown',
            ':-#':'Braces',
            '%-(':'Broken Glasses',
            '=((':'Broken Heart',
            '</3':'Broken Heart',
            '(U)':'Broken Heart',
            '(:^(':'broken nose',
            ':^)':'broken nose',
            ':-E':'buck-tooth',
            #':-E':'Buck-tothed',
            ':-(=)':'Bucktoothed',
            #':-E':'bucktoothed vampire',
            '}:-(':'bull headed',
            ':-c':'bummed out',
            ':-c':'Bummed out Smiley',
            ' U U ':'Bunny',
            '#:-)':'bushy hair',
            ':-#|':'Bushy Mustache',
            '(_|_)':'Butt',
            '}i{':'Butterfly',
            '}|{':'Butterfly',
            '})i({':'Butterfly',
            ':-c':'Call Me',
            '(p)':'Camera',
            ':-D':'Can’t keep mouth shut',
            ':()':'can’t stop talking',
            #'P=\\':'Cap',
            '~':'Cat',
            '=^.^=':'Cat',
            ">'o'<":'Cat',
            '>^..^<':'Cat',
            '>^,,^<':'Cat',
            '}:-X':'Cat',
            '(@)':'Cat Face',
            '>;3':'Cat Winking',
            'Q:-)':'atcher (baseball)',
            '(:@@@@@@@@@@@@@@@D':'catepillar (top view)',
            'C|:-=':'Charlie Chaplin',
            ';)':'Cheeky Wink',
            '\o/':'Cheer',
            '*\O/*':'Cheerleader',
            'C=:-)':'Chef',
            '(-: =3':'Chef',
            #'':'Cheshire cat',
            '8^':'Chicken',
            '~:>':'Chicken',
            #'C8o \\':'Chimp',
            'C8o )':'Chimp',
            'C8o (':'Chimp',
            ';-(':'Chin Up',
            '<|-)=':'chinese',
            '-{:-]':'Chinese Hat',
            '*<<<<=':'Christmas Tree',
            '*<<<<+':'Christmas Tree',
            '<{^-^}>':'Chubby Face',
            '=====~':'cigarette',
            '(ci)':'Cigarette ',
            ':-.)':'Cindy Crawford',
            '(:)':'Clam',
            ':)':'Classic Smiley',
            ':-)':'Classic Smiley',
            '(o)':'Clock',
            '<|:-()}':'Clown',
            '<|:^0|<':'Clown',
            '<]:o){':'Clown',
            '*<):O)':'Clown',
            '*<:O)':'Clown',
            '*:o)':'Clown',
            ':O)':'Clown',
            ':*)':'clowning',
            '(c)':'Coffee Cup',
            '?_?':'Cold Stare',
            'P-)':'Colonel Klink',
            '$:-)':'Comb Stuck in the Hair',
            ':-)':'Comedy',
            '(co)':'Computer',
            ':-r':'Concentrating',
            ':-8(':'Condescending stare',
            'O.o':'Confused',
            '%)':'Confused',
            '%-)':'Confused',
            '(@_@)':'Confused',
            ':s':'Confused',
            ':-S':'Confused',
            ':-Q':'Confused',
            ':-$':'Confused',
            ':-/':'Confused',
            ':-S':'Confusion',
            'B-)':'Cool',
            ':-{':'Count Dracula',
            '3:08':'cow',
            '3:-O':'Cow',
            #"+/'\\":'Cowbell',
            '<):)':'Cowboy',
            '<):-)':'Cowboy',
            '}:-)':'Cowboy',
            '{:-)':'Cowgirl',
            'V.v.V':'Crab',
            '%-)':'Crazy',
            ':-t':'cross',
            'H-)':'Cross-Eyed',
            '%-)':'cross-eyed',
            'T_T':'Crying',
            'T^T':'Crying',
            'QQ':'Crying',
            '=O ::::::':'Crying',
            "='(":'Crying',
            '&.(..':'Crying',
            '(;_;)':'Crying',
            ":'(":'Crying',
            ":'":'Crying',
            ":'-(":'Crying',
            ':*(':'Crying',
            ':*-(':'Crying',
            ':((':'Crying',
            ':..[':'Crying',
            ':_ (':'Crying',
            ':`-(':'Crying',
            ';_;':'Crying',
            ":'-(":'crying sadly',
            ':*(':'Crying Softly',
            ":'-)":'crying with happiness',
            ":'-)":'crying with joy',
            '|_|':'Cup',
            'C(_)':'Cup of Coffee',
            '~o)':'Cup of Coffee',
            '|_P':'Cup of Coffee',
            '&:-)':'curly hair',
            '@:-)':'Curly Hair',
            ':-@!':'Cursing',
            'o-)':'Cyclops',
            'O-(':'Cyclops',
            '0-)':'Cyclops',
            '*-(':'Cyclops got poked in the eye',
            '<(..<)':'Dancing',
            #'\\:D/':'Dancing',
            '(>..)>':'Dancing',
            '^(. .)^':'Dancing',
            'C8<]':'Darth Vader',
            'Q:|':'Davey Crockett',
            '8->':'Daydreaming',
            '*-*':'Dazed',
            '8-#':'Death',
            ':-| :-|':'Deja Vu',
            ':-9':'delicious, yummy',
            ':-[':'Despondent',
            '>:)':'Devil',
            '>:-)':'Devil',
            '}=^{|~':'Devil',
            '}:-)':'Devil',
            ']:->':'Devil',
            '()}:o)':'Devil',
            '-6':'Devil',
            '>:->':'Devilish',
            '}:->':'Devilish',
            ':->':'Devilish',
            ':>':'Devilish Grin',
            ';->':'devilish wink',
            #'/\':'Dinosaur',
            #'=\':'Disappointed',
            ':|':'Disappointed',
            ':(&':'Disappointed',
            ':-E':'Disappointed',
            ':-|':'Disappointed',
            ':-e':'disappointed smiley',
            'DX':'Disgusted',
            '/:(':'Distraught',
            '%-}':'Dizzy',
            'd[-_-]b':'DJ',
            '[:-}':'DJ',
            'd^_^b':'DJ wearing head phones',
            ':-$':'Do Not Tell Anyone',
            ':-#':'Do Not Tell Anyone',
            '<[.,=.,]-':'Dog',
            ':O$':'Dog',
            #":O\'":'Dog',
            ':O/':'Dog',
            ':O)':'Dog',
            ':O?':'Dog',
            ':3-<':'Dog',
            ':3-]':'Dog',
            '8==3':'Dog Bone',
            '&===3':'Dog bone',
            '(&)':'Dog Face',
            '(>.<)':'Doh',
            '#-o':'Doh!',
            ':-) 8':'Dolly Parton',
            ':$)':'Donald Trump',
            ':-))':'double chin',
            '}:-(=':'Dracula',
            ':-(':'Drama',
            '(:-|K-':'Dressed To Kill',
            '\_/':'drink',
            '*DRINK*':'Drink',
            ':*)':'Drinking Every Night',
            ':-). . .':'drooler',
            '=P~':'Drooling',
            '*DROOLING*':'Drooling',
            ':P':'Drooling',
            ':-P':'Drooling',
            ':-)~':'Drooling',
            ':-P```':'Drooling (sees food)',
            ':-B':'Drooling Out Of Both Sides Of Mouth',
            ':~)':'drunk',
            ':#)':'Drunk',
            ':*)':'drunk',
            ':-}':'drunk',
            ':*)':'drunk smile',
            '%-':'drunk with laughter',
            './':'Duck',
            '8)':'Dumb Person',
            '<:-)':'Dumb Question',
            '<:-)':'dumb questions',
            '<:I':'Dunce',
            '<:-)':'dunce',
            '<:-(':'Dunce',
            #'':'dunce',
            '(e)':'E-mail',
            '<:-0':'Eeek!',
            '(:I':'Egghead',
            ':~':'Elephant',
            '2:)':'Elvis',
            '@=)':'Elvis',
            '5:-)':'Elvis Presley',
            '&:-/':'Elvis, curly hair',
            ':")':'Embarrased',
            ':$':'Embarrassed',
            ':-$':'Embarrassed',
            ':-[':'Embarrassed',
            ':-}':'Embarrassed Smile',
            'T-T':'Emo',
            '//_^':'Emo',
            '(//.^)':'Emo',
            '(//_^)':'Emo',
            '0|-)':'Enjoying The Sun',
            '>:)':'Evil',
            '(.\|/.)':'Evil Face',
            '>-)':'Evil Grin',
            ':-O':'Excited',
            ':@':'exclamation',
            '#-)':'Exhausted',
            ':-6':'exhausted, wiped out',
            ':-@':'extremely angry',
            '8-)':'Eye-Rolling',
            '}=D':'Eyebrows',
            '-@--@-':'Eyeglasses',
            '# -':'Eyepatch',
            '(p ^^)=====O':'Falcon Punch',
            '?:-)':'Fancy Hair',
            'o,..,o':'Fangs',
            '^,..,^':'Fangs',
            '>-':'Female',
            '/ | | |':'Fighting',
            '(~)':'Filmstrip',
            '(yn)':'Fingers Crossed',
            '><(((">':'Fish',
            '<><':'Fish',
            '<*))))><':'Fish',
            '<((((><':'Fish',
            '<")))><':'Fish',
            '<.{{{><':'Fish',
            '}-(((*>':'Fish',
            '{}{':'Fish',
            ';-)':'Flirty',
            '@>--;--':'Flower',
            '@>---':'Flower',
            ':-!':'Foot in Mouth',
            '()':'Football',
            'G:-)':'Football Helmet',
            '=:-H':'football player',
            '%%-':'Four Leaf Clover',
            '7:-)':'Fred Flintstone',
            '/:-)':'Frenchman With A Beret',
            #'':'Friends',
            '8)~~*':'Frog',
            '8)':'Frog',
            '<? ?>':'Frog',
            ':(?)':'Frog',
            '[II]D':'Frosty Mug',
            ':(':'Frown',
            ':-(':'Frown',
            '(:-(':'Frowning',
            ':-<':'Frowning',
            ':-(':'Frowning',
            '):-(':'Frowning Smiley With Hair',
            'X[':'Frustrated',
            '=P':'Frustrated',
            '><':'Frustrated',
            ' :// ':'Frustrated',
            ':-P':'Frustrated',
            ':-/':'Frustrated',
            '\~/':'full glass',
            '=:-)':'Funny Hair',
            '*:*':'Fuzzy Face',
            ': 0=/--':'Gag me',
            '8=:-)':'Galloping Gourmet',
            ':O':'gasp',
            '4:-)':'George Washington',
            ':-%':'Get Lost',
            'P-)':'getting fresh',
            '~~:-(':'Getting Rained On',
            '(g)':'Gift with a Bow',
            '*GIGGLING*':'Giggling',
            '>:o===Q<':'Giraffe',
            '8:^)':'Girl',
            '(x)':'Girl',
            '\_/':'glass empty',
            '8-)':'Glasses',
            '??':'Glasses',
            '-o-o-':'Glasses',
            '8*)':'Glasses And A Half Mustache',
            '8:-)':'Glasses on forehead',
            '(nah)':'Goat',
            ':-{>':'Goatee',
            ':-)>':'Goatee',
            '|-|':'Going To Sleep',
            'o/':'Golf Club and Ball',
            '8-)':'goofy smile or wearing glasses',
            '8:]':'Gorilla',
            '%:O':'Gorilla',
            ':8]':'Gorilla',
            '(~};)':'Grateful Dead',
            ':^D"':'Great! I Like It!',
            '$_$':'Greedy',
            ':-D':'grin',
            ':->':'Grin',
            ':O':'Grinning And Sticking Tongue Out',
            '(____)':'Guitar',
            '$8()':'Guy with a Toupee',
            '#:-)':'Hair In A Mess',
            '{:-)':'hair parted in middle, toupee',
            '{:-)':'hair parted in the middle',
            '}:-)':'Hair Parted In The Middle Sticking Up On Sides',
            '=:-)':'Hair Standing On End',
            '(^:^)':'Halloween pumpkin',
            'E:-)':'ham radio operator',
            'E-:-)':'ham radio operator',
            '(%)':'Handcuffs',
            ':-3':'Handlebar Mustache',
            ':-})':'Handlebar Mustache',
            '&:-]':'Handsome',
            'U':'Happy',
            '|___|':'Happy',
            '=)':'Happy',
            ':)':'Happy',
            ':->':'Happy',
            ':-)':'Happy',
            '^.^':'Happy',
            '^?^':'Happy',
            '^-^':'Happy',
            ' :-)':'Happy',
            '3:8)':'happy cow',
            '%-)':'Happy Drunk',
            ':@)':'happy pig',
            '<~8)':'Harry Potter',
            '>O<':'Harry Potter Snitch',
            '/* *':'Harry Potter Wand',
            ":-'":'Has A Dimple',
            ':-#':'Has Braces',
            ':-)}':'has goatee/beard',
            '-:-)':'has mohawk',
            ':=)':'has two noses',
            '<<<<(:':'hat salesman',
            '<<<<(:-)':'hat salesman',
            'D:-)':'Hats Off To Your Great Idea',
            ':-`|':'Have A Cold',
            ':-|':'have an ordinary day Emoticon',
            '(({..}))':'Headache',
            '<u3':'Heart',
            '<3':'Heart',
            '(:-...':'Heart-broken',
            '|:-)':'Heavy Eyebrows',
            ':-{}':'heavy lipstick',
            '|-)':'Hee-hee',
            '|-)':'Hee-hee',
            ':->':'Hey',
            ':->':'Hey hey',
            '(h5)':'High Five',
            '^5':'high five',
            ':-I':'Hmmm',
            ':-|':'Hmmm',
            #':-\':'Hmmm',
            ':-/':'Hmmm',
            ':-,':'Hmmmm',
            '|-D':'Ho ho',
            'L.':'Hockey Stick and Puck',
            '8-)':'Hollywood',
            '(8-(1)':'Homer',
            '(_8^(|)':'Homer',
            '( o ) ( o )':'hooters',
            'B-)':'Horn-rims',
            '[_]':'Horror',
            '(h)':'Hot',
            '{ }':'Hug',
            '((((name))))':'Hug',
            '(:)\/<':'Hug',
            ':)X':'Hug',
            '<(^.^<)':'Huge',
            '<(*.*<)':'Huggle',
            '((()))':'Hugs',
            ':D<':'Hugs',
            '{{{***}}}':'Hugs and Kisses',
            '(()):**':'hugs and kisses',
            ':-)':'Humor (or smiley)',
            '%*@:-(':'Hung Over',
            #'%-\':'hungover',
            ':0':'Hungry',
            'XD':'Hyper',
            '@-)':'Hypnotized',
            'O[-<]:':'I Am A Skater Or I Like To Skate',
            ':[':'I Am A Vampire!',
            '((:-/':'I Am Bald',
            ":'-(":'I Am Crying',
            '?$?:-)':'I Am Rich!',
            ">;-('":'I Am Spitting Mad',
            ':^)':'I Do Not Know',
            ':-) .':'I Have An Outie Belly Button',
            ':-) ,':'I Have An Outie Belly Button',
            '#;-)':'I Have Tangled Hair',
            '<3':'I Love You',
            ':-E':'I’m Disappointed',
            ':+(':'I’m Hurt By That',
            '(-.-)ZZZ':'I’m Sleepy',
            ":'-)":'I’m So Happy I’m Crying',
            ':*)':'I’m Tipsy',
            '%-)':'I’m Tipsy But Happy',
            'B-)':'I’m Wearing Glasses',
            '~oO>':'Ice Cream Cone',
            '<><':'Ichthus',
            '(:-$':'ill',
            '*red+u':'IM',
            '*help':'IM',
            '(@)':'In Love',
            '*IN LOVE*':'In Love',
            '(*_*)':'In Love',
            ':-X':'In Love',
            '._.':'Inadequate',
            ':-S':'Incoherent',
            ':7/':'Indecisive',
            ':-I':'Indifferent',
            ':-|':'Indifferent',
            '8':'Infinity',
            'O:-)':'Innocent',
            '%7<':'Irritated',
            '?_?':'Irritated',
            '(ip)':'Island with a Palm Tree',
            '?:^[]':'Jim Carrey',
            ':###)':'Jimmy Durante',
            '8-)':'Joe Cool',
            #'//o-o\\':'John Lennon',
            '(8 {':'John Lennon',
            '@:-)':'John Travolta With ‘Grease’ Quiff',
            'X-p':'Joking',
            '*JOKINGLY*':'Jokingly',
            ':-]':'Jovial',
            '8-*':'just ate a hot pepper',
            '@:-}':'Just Back From Hairdresser',
            ':-T':'Keeping A Straight Face',
            ':-X':'Kid Smiley',
            '\VVV/':'King',
            '\$$$/':'King',
            "<('.'<)":'Kirby',
            '<(^.^)>':'Kirby',
            "<( '.' <)":'Kirby',
            "<( '.' )>":'Kirby',
            "(>'.')>":'Kirby',
            '=':'Kiss',
            '*':'Kiss',
            ':*)':'Kiss',
            ':-*':'Kiss',
            ':-)*':'Kiss',
            ';-(!)':'Kiss',
            '(_X_)':'Kiss My Butt',
            '*KISSED*':'Kissed',
            ':*':'kisses',
            ':}{:':'Kisses',
            '*KISSING*':'Kissing',
            '(}{)':'Kissing',
            '(:-*':'Kissing',
            "( '}~{' )":'Kissing',
            "( '}{' )":'Kissing',
            ':pd:':'Kissing',
            '=+=':'Kitty',
            '=^w^=':'Kitty',
            '=^.^=':'Kitty',
            ':3':'Kitty',
            '@(*o*)@':'Koala',
            ':*)O':'Kool',
            '<{::}>':'Ladybug',
            '(::)<':'Ladybug',
            'C:-)':'large brain capacity',
            'l8r)':'Later',
            ':-D':'Laugh Loud',
            'XD':'Laughing',
            ':))':'Laughing',
            ':-D':'Laughing',
            ';-D':'laughing',
            ':-D':'laughing (at you!)',
            '%OD':'Laughing Like Crazy',
            '=D':'Laughing out Loud',
            '%-(I)':'laughing out loud',
            ':.-)':'Laughing Tears',
            '(-:':'Left Hand',
            '(-:':'Left Hand Smiley!',
            '?-:':'Left Handed Tongue Touching Nose',
            '({)':'Left Hug',
            '(-:':'left-handed',
            ')-:':'Left-handed Sad Face',
            '(-:':'Left-handed Smiley Face',
            '>;->':'Lewd Remark',
            ':^o':'Liar Liar',
            ':-9':'Licking Lips',
            '(i)':'Light Bulb',
            '(li)':'Lightning',
            '%-)':'Like My New Glasses',
            ';-,':'Like, Duh',

            '(:)-)':'likes to scuba dive',
            ':3':'Lion',
            ':X':'Lips are Sealed',
            ':-X':'Lips are Sealed',
            ':-#':'Lips are Sealed',
            ':-*':'Lips are Sealed',
            ':()':'Lipstick',
            '[:-)':'listening to Walkman radio',
            '8:-)':'little girl',
            ':~)':'Long Nose',
            ':-----)':'long nose (Liar!)',
            '<@> <@>':'Look at Me',
            '>_>':'Looking',
            '<_<':'Looking',
            '(*)?(*)':'Looking',
            '<.< >.>':'Looking Around',
            '<o?o>':'Looking at You',
            '<*_*>':'Looking at You',
            ':-?':'Lopsided grin with dimple',
            'L-)':'Loser',
            '%+{':'lost a fight',
            ':-{}':'Lots of Lipstick',
            ':-) :-) :-)':'loud guffaw',
            '<3':'Love',
            '(>^.^)> <3 <(^.^<)':'Love',
            ':x':'Love Struck',
            '(m)(m)(m)':'',
            'X-(':'M&Ms',
            '~:(':'Mad',
            '=/':'Mad',
            '>=[':'Mad',
            '>=(':'Mad',
            '>:-<':'Mad',
            '>,<':'Mad',
            ';-(':'Mad Look',
            '>:-(':'mad, annoyed',
            ':-.)':'Madonna',
            '&-L':'Makes Me Cry',
            ':-(*)':'Makes Me Sick',
            ':-S':'Makes No Sense',
            ':-':'male',
            '@@@@@:-)':'Marge Simpson',
            '@@@@:-)':'Marge Simpson',
            '(#-[':'Marine',
            ':-)(-:':'Married',
            '(d)':'Martini Glass',
            '3:[':'mean pet smiley',
            '#:-)':'Messy Hair',
            '\m/':'Metal',
            #'�O�':'Mickey Mouse',
            '8(:-)':'Mickey Mouse',
            'o/<':'Midget',
            ':)':'Midget',
            'o|-<':'Midget person',
            ':>':'midget smiley',
            ':)':'midget smiley',
            ':<':'midget unsmiley',
            ':p':'Mischievous',
            ':~/':'mixed up',
            '(mp)':'Mobile Phone',
            '^o^':'Mog',
            '~~:-(':'Mohawk',
            '(mo)':'Money',
            '$-)':'Money Eyes',
            ':-$':'Money Mouth',
            'U':'Monkey',
            '@(-_-)@':'Monkey',
            '---':'Monkey',
            '@(^_^)@':'monkey face',
            ':E':'Monster',
            '(00)':'mooning you',
            '(|)':'Mooning You',
            '(_i_)':'Mooning You',
            'oO~':'Mouse',
            '~<>^>':'Mouse',
            '<:3)~~':'Mouse',
            '<:3)~':'Mouse',
            '<:3 )~':'Mouse',
            '8(:-)':'Mousketeer',
            ':-{)':'Moustache',
            ':-{':'Moustache',
            ':-{)}':'Moustache And Beard',
            ':-{)':'moustache man',
            '8-o':'Mr. Bill',
            '~O-O~':'Mr. Magoo',
            '(m)':'MSN Messenger',
            'l_l)':'mug',
            '={D':'Mustache',
            '{ 8{]':'Mustache',
            ':{':'Mustache',
            ':-{':'Mustache',
            ':-{)=':'Mustache & Goatee',
            '{:-{)}':'Mustache And Beard',
            ':-:':'mutant',
            ':-#':'My Lips Are Sealed',
            ':-x':'my lips are sealed Emoticon',
            ':-SS':'Nailbiting',
            '~,~':'Napping',
            ':-P':'Naughty',
            '*:-)':'Navy Admiral',
            '@:-)':'Navy Captain',
            '#:-)':'Navy Commander',
            '=:-)':'Navy Lieutenant',
            '(-)':'needs a haircut',
            '8-|':'Nerd',
            '*8-I':'Nerd',
            ':-B':'Nerd',
            'E-:-I':'net.ham-radio',
            'Q:-)':'new graduate',
            '{}':'No Comment',
            ':-X':'no comment',
            '|:-0':'No Explanation',
            ':-|':'No expression',
            ':-|':'No expression face, ‘that comment doesn’t phase me’',
            ':/i':'no smoking',
            '):-(':'Nordic',
            '8:]':'Normal smiling face except that a gorilla',
            ':/)':'Not Amused',
            ':/)':'not funny',
            '=:-)':'Not much better hair day',
            '[-(':'Not talking',
            '-8':'Note',
            ':-O':'Oh',
            '8-O':'Oh My God!',
            ':-O':'Oh No',
            '#:-O':'Oh No!',
            '#:-o':'Oh, nooooooo!',
            '?:-_]':'Old Lady',
            '|:-{)~':'Old Man',
            ':-=)':'Older user with mustache',
            ':)]':'On the Phone',
            '.-]':'one eye',
            '.-)':'one eye',
            ',-)':'one eye … and winking',
            "':-(":'One Eyebrow',
            "':-�":'one eyebrow raised',
            '�-)':'One-Eyed Smile',
            "'-)":'One-Eyed Smile',
            '=X':'Oops',
            ':-*':'Oops',
            '=^)':'Open-minded',
            ':d':'Open-Mouthed Smile',
            ':-D':'Open-Mouthed Smile',
            ':=)':'Orangutan',
            ':@':'Ouch!',
            '^_^':'Overjoyed',
            '(^o^)':'owl',
            #'':'Owl',
            '<.....':'Pac-man',
            '(<. . . . .':'Pacman',
            '(:V)':'Pacman',
            ':v':'Pacman',
            ':-[':'particularly angry',
            '#-)':'partied all night',
            '<:o)':'Party',
            '<:-P':'Party',
            '<l:0':'Partying',
            '*<(8)~/~<':'Partying',
            '*<|8-P~':'Partying Too Much',
            '(:V':'Pato',
            '(/|\)':'Peace',
            ':)>-':'Peace',
            '8>':'Penguin',
            ':-?':'Pensive',
            ':-/':'Perplexed',
            '<:^]':'Person',
            '@-)':'Person submitting is Cyclops',
            ':^)':'Personality',
            '3:]':'Pet Dog',
            '3:]':'pet smiley',
            '>:P':'Phbbbbt',
            ':?)':'philosopher',
            #'%\v':'Picasso',
            '%-^':'Picasso',
            '----|}':'Pie Being Thrown',
            'o()~':'Pig',
            '=8)':'Pig',
            ':8)':'Pig',
            ':@)':'Pig',
            ':(:)':'Pig',
            '(o^-^o)':'Pikachu',
            "^_^''":'Pikachu',
            '(_)':'Pineapple',
            ':---)':'Pinnochio',
            ':-------[':'Pinocchio',
            ':-?':'pipe smoker',
            'P-(':'Pirate',
            '<|':'Pizza',
            '<%)':'Pizza',
            '(pi)':'Pizza',
            '(pl)':'Plate',
            ':-<':'Pointy Mustache',
            '}:^#)':'Pointy Nosed',
            ':-I':'Poker Face',
            '[::::]':'Pop-Tart',
            '****':'popcorn',
            '+O=-)':'Pope',
            #':-\':'Popeye',
            #';-\':'Popeye gets his lights punched out',
            #':-\':'Popeye smiling face, for people who look like popeye',
            ':-T':'Pouting',
            ':-[':'pouting',
            ':-[':'Pouting Variation',
            'O/':'Praise The Lord',
            '[-o<':'Praying',
            '&&&&':'pretzels',
            '\<><>/':'Prince',
            '~<:-)':'Princess',
            '\&&&/':'Princess',
            ';~[':'Prizefighter',
            '(+[ ]-:-)':'PSP',
            ':-#':'punched in the mouth',
            '=:-)':'Punk',
            '=:-(':'Punk Not Smiling',
            "Q('.'Q)":'Put Em Up',
            ':-$':'Put Your Money Where Your Mouth Is',
            ':-($)':'put your money where your mouth is',
            #'\%%%/':'Queen',
            '=:>)':'rabbit',
            '(___)0':'Rabbit',
            '/:)':'Raised Eyebrow',
            ':-R':'Rasberry',
            '=:7)~~':'Rat',
            '=:7(~~':'Rat',
            '--- :':'Rat',
            ':-<':'real sad smiley',
            ':-<':'real sad smiley',
            ':-C':'Real Unhappy',
            '~:-(':'Really Bummed Out',
            ':-C':'really bummed out',
            ':-$':'Really confused',
            '=D':'Really Happy',
            ':-))':'Really Happy',
            '()_RED_(>':'Red Crayon',
            '(l)':'Red Heart',
            '(k)':'Red Lips',
            '(f)':'Red Rose',
            '}---:o>':'Reindeer',
            '+-(:-)':'Religious leader',
            '~o)':'Reproduction',
            '>=D':'Revenge',
            '(})':'Right Hug',
            '<(-_-)>':'robot',
            '[:]':'Robot',
            '\m/>.<\m/':'Rocker',
            '\m/(**)\m/':'Rocker',
            '\m/ >_< \m/':'Rocker',
            '>-D':'Rocking',
            '\w/^^,\w/':'Rocking',
            '\m/':'Rocking',
            '9_9':'Rolling Eyes',
            '8-|':'Rolling Eyes',
            '>>':'Rolling Eyes',
            '=))':'Rolling on the floor laughing',
            '7:)':'Ronald Reagan',
            '7:-)':'Ronald Reagan',
            '7:^]':'Ronald Reagan',
            "@~'~~~":'Rose',
            '@~)~~~~':'Rose',
            '@>-;--':'Rose',
            "@}>-'-,--":'Rose',
            '@};-':'Rose',
            '@};---':'Rose',
            '@}->--':'Rose',
            '@)->-':'Rose',
            '@->--':'Rose',
            '@-}----':'Rose',
            '@>;-----':'rose, opening with leaves',
            '3:*>':'Rudolph the reindeer',
            'Y_Y':'Sad',
            'T.T':'Sad',
            'D=':'Sad',
            'D:':'Sad',
            '=[':'Sad',
            '=(':'Sad',
            '(<_>)':'Sad',
            ':c':'Sad',
            ':*(':'Sad',
            ':[':'Sad',
            ':(':'Sad',
            ':-(':'Sad',
            '/:-)':'Sailor',
            '*<|:-{)}':'Santa Claus',
            '*<|:-)':'Santa Claus',
            '*<|:^) }':'Santa Claus',
            '*<:-)':'Santa Claus',
            '*<|:-)':'Santa Claus (Ho Ho Ho)',
            ':-7':'Sarcastic',
            ';->':'Sarcastic',
            '^o)':'Sarcastic',
            '*!#*!^*&:-)':'schizophrenic',
            '!:-)':'Scholar',
            '8<':'Scissors',
            ':-@':'scream',
            ':-@':'screaming',
            '0-)':'scuba diver',
            ')8-)':'Scuba Smiley big-face',
            #"\';./":'Sea Horse',
            '(-_-)':'secret smile',
            ':-*':'Secret Telling',
            '::=))':'Seeing Double',
            '8==8':'Seeing Eye to Eye',
            '$-)':'Sees Money',
            ':-I':'Semi-Smile',
            ':-i':'Semi-Smiley',
            '&:-)':'Sender Has Curly Hair',
            '(-:':'Sender Is Left-handed',
            '8-)':'Sender Wears Glasses',
            '[-x':'Shame on You',
            '<(((">':'Shark',
            ',:-)':'Shaved Left Eyebrow',
            'o_o':'Shocked',
            '35277':'Shocked',
            '=o':'Shocked',
            '*SHOCKED*':'Shocked',
            ':-o':'Shocked',
            ':-O':'shocked, surprised',
            '+-(':'Shot Between The Eyes',
            '^^':'Shoulder Shrug',
            ':-V':'Shouting',
            '(*^_^*)':'Shy',
            '(-::-)':'Siamese twins',
            '=+o()':'Sick',
            ':-s':'Sick',
            ':-&':'Sick',
            ':-(*)':'Sick Comment',
            ':-Y':'Sick Comment',
            ':-<':'Sigh',
            '8-}':'Silly',
            '=P':'Silly',
            '(c:':'silly nose',
            '(^o^)':'Singing',
            ':O':'Singing',
            ':-o':'Singing',
            '(^o^)':'singing or laughing',
            '~:-P':'Single Hair',
            'o{-<]:':'Skateboarder',
            'O-\-<]:':'Skateboarder',
            '0-<-<):':'Skateboarder',
            'o<[^(':'Skater',
            ':-/':'skeptical',
            ';-/':'skeptical',
            "':-/":'Skeptical Again',
            ':-7':'Skeptical Variation',
            '8-X':'Skull',
            '(>.<) zzZ':'Sleeping',
            '(s)':'Sleeping Half-Moon',
            'u_u':'Sleepy',
            '|-)':'Sleepy',
            '#)':'Sleepy',
            '(>.<)':'Sleepy',
            "#(,'%/)":'Slept Too Long',
            '%-)':'sly',
            'C:':'Smile',
            '=o)':'Smile',
            '=)':'Smile',
            '[______]':'Smile',
            ':o)':'Smile',
            ':|)':'Smile',
            ':)':'Smile',
            ':-)':'Smile',
            'B-)':'smile and wearing sunglasses',
            '=)':'Smile!',
            '(^_^)':'smiley',
            'O-)':'Smiley After Smoking A Banana',
            ':-%':'smiley banker',
            '(:-)':'Smiley big-face',
            ':-]':'Smiley blockhead',
            ':-9':'smiley licking it’s lips',
            '+:-)':'Smiley priest',
            '=:-#}':'Smiley punk with a mustache….',
            '=:-)':'smiley punk-rocker',
            ':-?':'smiley smoking a pipe',
            ':-)':'smiley standard',
            '(:-#':'smiley with braces',
            '):-)':'Smiley With Hair',
            '{:-)':'Smiley with its hair parted in the middle',
            'g-)':'Smiley with ponce-nez glasses',
            ':^J':'Smiling',
            '^&^':'Smiling',
            '^^':'Smiling',
            ':-1':'Smirk',
            ':-,':'Smirk',
            ':^,':'Smirking',
            ';^)':'Smirking',
            ':-Q':'Smoker',
            ':-7':'smokes a pipe',
            ':-Q':'Smoking',
            ':-d':'Smoking',
            ':-?':'smoking a pipe',
            ':>':'Smug',
            '@x':'Snail',
            '(sn)':'Snail',
            '~~~~8}':'Snake',
            '(so)':'Soccer Ball',
            '?-(':'Sorry',
            'X P':'Sour Face',
            '=.=':'Sour Face',
            '(X^(*':'Sour Face',
            '}:8>':'Spanish bull',
            ':-M':'Speak no Evil',
            ':-W':'speak with forked tongue',
            ':-x':'speechless',
            ':-`':'spitting out chewingtobacco',
            ':-( <|':'Standing Firm',
            '(*)':'Star',
            '*~*':'Star Gazed',
            '%-)':'Staring At A Screen For Too Long',
            #'/ \':'Stick Man',
            ':-P':'sticking out tongue',
            ':-p':'sticking their tongue out (at you!)',
            '>:P':'Sticking Tongue Out',
            ':pp':'Sticking Tongue Out',
            ':P':'Sticking Tongue Out',
            ':-r':'Sticking Tongue Out',
            ':-P':'Sticking Tongue Out',
            ':-)~':'Sticking Tongue Out',
            '$:-$':'Stock Broker',
            '*STOP*':'Stop',
            '(st)':'Stormy Cloud',
            ':|':'Straight face',
            '-.-':'Stressed',
            '@?@':'Stunned',
            '&;-P':'Suave',
            'B-)':'Sunglasses',
            '8-)':'sunglasses',
            'B:-)':'sunglasses on head',
            'B :-)':'Sunglasses on top of head',
            '(8-{)}':'Sunglasses, Mustache, Beard',
            '/8^{~':'Sunglasses, Mustache, Goatee',
            '(#)':'Sunshine',
            ':-<':'super sad',
            "    /'":'Surfer',
            ':-o':'surprise',
            'U':'Surprised',
            '\m/<(^_^)>\m/':'Surprised',
            '*SURPRISED*':'Surprised',
            '{:o':'Surprised',
            '(:-)':'Surprised',
            ':o':'Surprised',
            ':0':'Surprised',
            ':-o':'surprised, worried',
            '8-|':'Suspense',
            ':#':'Swearing',
            '`:-)':'Swearing',
            'oxx:{}:::::::>':'Sword',
            '/________|___|':'Sword',
            '---(|||]==[]':'Syringe',
            '=;':'Talk to the Hand',
            ':-0':'Talkative',
            ':-D':'Talking',
            ':-{ }':'Talking',
            ':^y':'Talking',
            ':-8':'talking from both sides of mouth',
            ':-S':'Talking Gibberish',
            ':-v':'Talking head Smiley',
            '&-|':'Tearful',
            '(t)':'Telephone Receiver',
            '-(:)(0)=8':'Teletubby',
            '>[I':'Television',
            ']:->':'The Devil',
            '0:-)':'the other halo',
            '+-(:-)':'the pope',
            '(:>-<':'thief: hands up!',
            ':-)---':'Thin As A Pin',
            '*-)':'Thinking',
            ':-I':'thinking',
            ':-?':'Thinking',
            '(n)':'Thumbs Down',
            '*THUMBS UP*':'Thumbs Up',
            '(y)':'Thumbs Up',
            '^':'thumbs up',
            '^-^':'tickled/giggling',
            ':-t':'Time Out',
            '=_=':'Tired',
            '*TIRED*':'Tired',
            '(:|':'Tired',
            '0000(0)(0)0000':'Toes',
            '8-;)':'Tongue in Cheek',
            ':-J':'Tongue in Cheek',
            ':-p':'tongue sticking out',
            ':-?':'Tongue Sticking Out',
            ':-&':'tongue tied',
            ':-&':'tongue tied, don’t know what to say',
            ':-A':'Tongue Touching Nose',
            ':-&':'tongue-tied',
            '*!#*!^*&:-':'Total Head Case',
            ':-C':'Totally Unbelievable',
            ':-J':'tounge in cheek',
            ':-r':'tounge out',
            ':-P':'tounge sticking out',
            ':-&':'tounge tied',
            '=-HHHH':'Tower',
            '>:-|':'Trekkie',
            ':-)))':'Triple Chin',
            '@:I':'Turban',
            '<:>==':'Turkey',
            '(tu)':'Turtle',
            ':=)':'two noses',
            ':-O':'Uh oh',
            '=-o':'Uh-oh',
            '(o|o)':'Ultraman',
            '(um)':'Umbrella',
            ':-(':'un-smiley',
            'X:-/':'Uncertain',
            ':-$':'uncertainty',
            '=):-)':'Uncle Sam',
            #':\':'Undecided',
            #':-\':'Undecided',
            ':-/':'Undecided',
            #':-\':'Undecided user',
            ':-|':'Unfazed',
            '|:-)':'Unibrow',
            '**==':'United States Flag',
            '):-(':'UnSmiley big-face',
            '(:-(':'unSmiley frowning',
            '|:-|':'Unyielding',
            '>.<':'Upset',
            '>:*':'Upset',
            '}:(':'Upset',
            ':-s':'User after a BIZARRE comment',
            ':-7':'User after a wry statement',
            ':-*':'User after eating something bitter',
            ':-6':'User after eating something sour',
            ':<|':'User attends an Ivy League school',
            ':-@':'User face screaming',
            ':-*':'User just ate a sour pickle',
            ':-9':'User licking it’s lips',
            '(:)-)':'User likes to scuba dive',
            '(-)':'User needing a haircut',
            '>-)':'User only has a left eye, which is closed',
            '#-)':'User partied all night',
            ':-o':'User singing national anthem',
            ':-`':'User spitting out its chewing tobacco',
            '-:-)':'User sports a mohawk and admires Mr. T',
            ':-D':'User talks too much',
            ':-)>':'User tends to drool',
            '0-)':'User wearing scuba mask',
            ':-#':'user wears braces / lips are sealed',
            '8-)':'User wears glasses',
            '::-)':'User wears glasses',
            ':-}':'User wears lipstick',
            ':-&':'User which is tongue-tied',
            ':-#|':'User with bushy mustache',
            ':u)':'User with funny-looking left nose',
            ':n)':'User with funny-looking right nose',
            '}(:-(':'User, wearing toupee in wind.',
            ':-@':'User’s beard has permanent wave *or* was drawn by Picasso',
            ':~)':'User’s face needs a nosejob, no explanation necessary',
            ':-#':'User’s lips are sealed.',
            '@,.,@':'Vampire',
            "(';.;')":'Vampire',
            ':-E':'Vampire',
            ':-[':'Vampire',
            ':[':'Vampire Bat',
            ':-[':'Vampire Bat',
            ':-[':'Vampiro',
            '%*}':'Very Drunk',
            ':-)))':'Very Happy',
            ':-))':'Very Happy',
            ':-[]':'Very hungry',
            ':-)))':'very overweight',
            #'(:-\':'VERY sad',
            ':-O':'very shocked or yelling',
            "%')":'Very Tired',
            '(:-(':'Very Unhappy',
            '(o^_^)o':'Victory',
            ':-w':'Waiting',
            '[:-)':'walkman',
            ':-<':'Walrus',
            ':-h':'Wave',
            '@:-)':'wavy hair',
            ':-X':'wearing a bow tie',
            ':-)X':'wearing a bowtie',
            'd:)':'wearing a cap',
            'D:-)':'Wearing A Sailor Hat',
            '{(:-)':'Wearing A Toupee',
            '{:-)':'wearing a toupee',
            '@:-)':'Wearing A Turban',
            '[:-)':'wearing a walkman',
            ':-#':'wearing braces',
            'B-|':'wearing cheap sunglasses',
            '8-)':'Wearing Contacts',
            'B-)':'Wearing Glasses',
            '(|:-)':'wearing headband',
            ':-{}':'Wearing Lipstick',
            'B-)':'Wearing Sunglasses',
            '8-)':'Wearing Sunglasses',
            ']-I':'Wearing Sunglasses',
            '{(:-)':'wearing toupee',
            '}:-)':'wearing toupee in an updraft',
            '{(:-)':'wearing toupee.',
            '(8-)':'wears glasses',
            '::-)':'wears glasses',
            ':-)8':'well dressed',
            ':-P':'Whatever',
            ':-1':'Whatever',
            '-_-':'Whatever',
            '*WHINING*':'Whining',
            ":'(":'Whining',
            ":'-(":'Whining',
            ':-"':'Whistling',
            '8-)':'wide-eyed',
            ';^?':'Wigged Out',
            '(w)':'Wilted Rose',
            '())=(':'Wine Glass',
            "'-)":'Wink',
            '(`_^)':'Wink',
            ';p':'Wink',
            ';O)':'Wink',
            ';)':'Wink',
            ';-P':'Wink',
            ';-)':'wink',
            '~_^':'Winking',
            "'-)":'Winking',
            ';)':'Winking',
            ';-)':'Winking',
            ',-)':'Winking Happy',
            ';-)':'winking smiley',
            ';-)':'Winking Variation',
            '<):^/':'Witch',
            ':-)X':'With a bow-tie',
            '*|:-)':'With a hat',
            '8<:-)':'Wizard',
            '8 :-)':'wizard',
            '-=#:-)':'wizard',
            '-=#:-) /':'Wizard With Wand',
            ':-)8 :':'Woman',
            '$-)':'won the lottery',
            ':~)':'Wondering',
            ':-S':'Worried',
            ':-O':'Wow!',
            ',-}':'Wry and winking',
            ':-7':'Wry Face',
            ':-7':'Wry Remark',
            '(xx)':'Xbox',
            '_/)':'Yacht',
            '|-O':'Yawn',
            '(:|':'Yawn',
            '|-O':'Yawning',
            '|-()':'Yawning',
            ':-@':'Yawning',
            '|^O':'Yawning Or Snoring Variation',
            ':-0':'yell',
            '>:O':'Yelling',
            ':-(0)':'yelling',
            '=:-0':'yeow !!',
            '@@(: l)':'yet another bad hair day',
            ':-l':'yet another smiley',
            #'8':'Yikes!',
            ':-0':'Yo !!',
            '<(-.-)>':'Yoda',
            '<(-_-)>':'Yoda',
            ':-(*)':'You Make Me Sick!',
            ':-( )':'You stepped on my toe',
            ':--------)':'You’re A Big Liar!',
            '(@ @)':'You’re kidding!',
            'X-(':'You’re Mad!',
            ':-0>':'Yuck Face',
            '|-P':'Yuk',
            '->=:-)':'Zippy the Pinhead',
}



emoticons2 = {":-)": "Felicidad sorpresa sonrisa",
             ":d":"Feliz",
             ":-D": "Me muero de risa",
             ":'-)": "Muy feliz",
             ":-(": "Triste",
             ":'-(": "Muy triste",
             ":-O": "Asombrado",
             ":-P": "Sacando la lengua",
             ";-)": "Sarcástico, guiñando un ojo",
             ":)": "Niño",
             ":(": "Niño triste",
             ":'(": "Niño llorando",
             ":-Q:": "Fumador",
             ":*)": "Borracho",
             "8-x": "Besucón",
             "8-)": "Con gafas",
             "[8-)": "Con gafas y pelo cepillo",
             "B-)": "Con gafas de sol",
             "B:-)": "Con gafas de sol en la cabeza",
             "::-)": "Con gafas normales en la cabeza",
             "{:-)": "Con tupé",
             ":-7": "Haciendo una mueca",
             ":-d": "Sacando la lengua",
             ":-{)": "Con bigote",
             ":-{}": "Con los labios pintados",
             ":-)~": "Babea",
             ":-~)": "Con moquillo",
             ":-@": "Gritando",
             ":-#": "Lleva tirantes",
             "P-)": "Guiñando un ojo II",
             ":'(": "Llorando",
             ":>)": "Narigudo",
             "8<:)": "Narigudo II",
             ":^)": "Nariz rota",
             ":v)": "Nariz rota en la otra dirección",
             ":_)": "Nariz deslizando fuera de la cara",
             ":=)": "Dos narices",
             "C8>[": "Calvo (por eso está triste)",
             ":-=": "Vampiro",
             ":-[": "Vampiro II",
             "D-]": "Cíclope",
             "S-{": "Mareado (o borracho II)",
             "|)": "Japonés",
             "<|-)": "Chino",
             "<|-(": "A este chino no le gustan estas bromas",
             ":0]": "Payaso",
             ">:-[": "Cabreado",
             ">>:-0": "Muy cabreado (cabreadísimo)",
             ":-1": "Relamiéndose",
             "<:-|": "Sereno  (¿?)",
             "=8-{}": "Asustado",
             "|-I": "Dormido",
             "|-O": "Bostezando",
             ":-?": "Fuma pipa",
             ":-D": "Riéndose  (de alguien)",
             "C=:-)": "Cocinero",
             ":-I": "Indiferente",
             "(-:": "Zurdo",
             "[:]": "Robot",
             ":-&": "Con la lengua atada",
             "-:-)": "Punky",
             "-:-(": "El buen punky no ríe",
             "O:-)": "Soy un santo",
             "};-)": "Diablillo",
             ">:->": "Diabólico",
             ">;->": "Diabólico y sarcástico",
             ":-]": "Simplemente contento",
             ":-$": "Hablando de dinero",
             "8-*": "Ooops ...qué he dicho!",
             ":-X": "Prefiero no decir nada. Me voy a callar",
             ":-/": "Escéptico. No me lo creo",
             "*-)": "En las nubes",
             ":->": "Después de hacer una gracia",
             ":-9": "Relamiéndose",
             "[:-)": "Con un walkman",
             "(:I": "Intelectualoide",
             "<:-I": "Zopenco",
             "@:-)": "Con turbante",
             ":-0": "No gritar",
             ":-:": "Smiley mutante",
             ".-)": "Solo tiene un ojo",
             "X-(": "Muerto",
             "8:-)": "Hechicero",
             ":]": "Enanillo amistoso",
             "%-)": "Cara que se le queda a un usuario de pantalla verde",
             ":*)": "El usuario está bebido",
             "+-:-)": "El Papa, o de alguna orden religiosa",
             "`:-)": "Se ha afeitado las cejas",
             ",:-)": "Se ha afeitado las cejas II",
             "@=": "A favor de la guerra nuclear",
             "E-:-)": "Operador de Ham Radio",
             "@--->---": "Una flor"
             }